/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118385-g0225fe857d-20250131"
#endif /* AVUTIL_FFVERSION_H */
